// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ComparisonTableController from "./comparison_table_controller"
application.register("comparison-table", ComparisonTableController)

import DescriptionController from "./description_controller"
application.register("description", DescriptionController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
